### ISSUE TITLE
Could not find generator webpack_rails:install.

### ISSUE THREAD

**Issue by danawoodman** [mipearson/webpack-rails#5] opened 2015-10-21 18:14 UTC
Using Rails 3.2.18 and Ruby 2.0 I'm getting the following when running `bundle exec rails generate webpack_rails:install` (after successful `bundle install` of `webpack-rails`):

```
Could not find generator webpack_rails:install.
```

Any idea what could cause this?

**Comment by mipearson** [comment] 2015-10-22 00:39
Reproduced here. I can see `webpack_rails:install` in the generators list but attempting to invoke it gives an error.

**Comment by mipearson** [comment] 2015-10-22 00:44
Fixed in 0.9.4

**Closed** 2015-10-22 00:43 UTC

**Comment by mipearson** [comment] 2015-10-22 00:46
btw, thanks for the report! I tested it, renamed the generator, and assumed it was "working" because I could see it in the generators list.
